name: Gen Task

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 */3 * *' # 3天一次 0点

jobs:
  Generate:

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2

      - name: 检查更新并生成markdown文档
        run: |
          chmod u+x ./gen.sh
          ./gen.sh 8
      - name: Push更新到当前仓库
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
